; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Button, gParar x104 y72 w80 h23, Parar
Gui Add, Button, gIniciar x24 y72 w80 h23, Iniciar
Gui Add, Slider, vforca x0 y0 w28 h221 +Vertical Invert Range1-2000, 50
Gui Add, Text, vTxtNormais x32 y8 w121 h23 +0x200, Normais:
Gui Add, Text, vTxtRaros x32 y40 w120 h23 +0x200, Raros:
Gui Add, Edit, vvariacoes x48 y136 w120 h21
Gui Add, Button, gSalvar x64 y160 w80 h23, Salvar

Gui Show, w197 h225, Macro NW
Return

Parar:
Return

Iniciar:
Return

Reiniciar:
Return

Salvar:
Return

GuiEscape:
GuiClose:
    ExitApp
